name: Custom deploy
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy'
        required: true
        default: 'container'
        type: choice
        options:
        - auth
        - container
        - dashboard
        - marketing

jobs:
  deploy-auth:
    if: ${{ inputs.service == 'auth' }}
    uses: ./.github/workflows/auth.yml
    secrets:
      inherit

  deploy-container:
    if: ${{ inputs.service == 'container' }}
    uses: ./.github/workflows/container.yml
    secrets:
      inherit

  deploy-dashboard:
    if: ${{ inputs.service == 'dashboard' }}
    uses: ./.github/workflows/dashboard.yml
    secrets:
      inherit

  deploy-marketing:
    if: ${{ inputs.service == 'marketing' }}
    uses: ./.github/workflows/marketing.yml
    secrets:
      inherit


